{% set version = "1.1.3" %}

package:
  name: conda-wrappers
  version: {{ version }}

source:
  url: https://raw.githubusercontent.com/gqmelo/exec-wrappers/{{ version }}/LICENSE
  sha256: 772e1576408f42a28de0cf235c1ab6753b0730c7121e4032d4a53882e9184ff1
  fn: LICENSE

build:
  number: 5

requirements:
  host:
    - python
  run:
    - python
    - exec-wrappers >=1.1,<2

test:
  commands:
    - create-wrappers --help

about:
  home: https://github.com/gqmelo/exec-wrappers
  license: MIT
  license_file: LICENSE
  summary: 'Simple package to execute exec-wrappers as a post-link action'

extra:
  recipe-maintainers:
    - gqmelo
