{% set version = "1.1.3" %}

package:
  name: conda-wrappers
  version: {{ version }}

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - exec-wrappers >=1.1,<2

test:
  commands:
    - create-wrappers --help

about:
  home: https://github.com/gqmelo/exec-wrappers
  license: MIT
  summary: 'Simple package to execute exec-wrappers as a post-link action'

extra:
  recipe-maintainers:
    - gqmelo
