travis:
  secure:
    BINSTAR_TOKEN: NTy7yeP5sbWJVjnP9InfIk6M76ncQ4nzok87gs1S9wCZ+AJzah1z3GpjvbBuf8p6563pOeLOpnzfZsXjKjG8Ez4cPM9WEKOo10iVVeOgrf4duf+hAwcJ7ESjMw1Dgx7iRHncbVHCKikVfZpBboAPY1OIJI7xp6lbMdq5t/q8RPVv+aivTcfNB/Kdo3ioG1gmcmIk1XT5efERpjvibiwRoE5BX4WxoE+w+RFy5KLyW5VHzOsSoQP/wAE+XkF6fR+kbhs3T8S37ivQdT4P9c4cVyqaHXHNJAmdX1n+XrsIt763sex0XtQdKOFhz4PIWPWLIBvlaC9uAz3Nn+gJpKNlphJhlwU5NuW00ZpMaR4OB4V7AcnZLyCrZzGNLihpSlxNMMX4Oa+/E90JD3jOX4Ap7Bt3wTDfkuOryb6LzKyxD5io+suB9u2s/BE8N3k751eHxrVzEujrVKf+TDBGrWkTC4eJ2BiOL6FSfJHyFxxyOHd/Jzk9Ybp6UaBsS6ORMiziOljpU1PznpWi/+9GMvTkihbwqEyCgOQ7SFbObttwMUo+LnxzeQliRtTwJIasiM5nlGttXt1MYIF1yZ3sqIdc9eordVi4GZ1/IJfNY6nYs0i9U08nisIkX/nlZXxQKT0bNrw7kW2Txp2j2tG1wSw+gQ8Ic/kj6RQEBuKpKHRPiWc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
