appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YfanHKk7NBL2L2s5wo8wtjV9NynPUt8K/OBT5Qe9RHxUwWVzg/zHvBVQlYnluWirLXeoZk1e7ZKL7JjA2chQuNO/vtE1ZG4kAMELl1uxU+6lT/KIJpVVhjzTucPoIgRzYhVTGYbAf6idLzTYI3O+SN6MP4OH1cNMYEoWahka2L2NKR7kmKbDRj8kOijZVe5koqJhcsjqc+3qOadfZiDNHWWZwW10lTLvcHHhEqNNjQdhqY1fObFRB6EaZf1zHIv6KFuGif0DqsH2waJXiTrcOZUCeI3S/rjVZcgei4Wj2ixlGpoBo+l5tpMTbhG5P2SKaahcylLSGl1ii5BybILxb5d1NzwuwCPWfZnVWEI5x9ijdmry7kGmiL3CgFYZtZJ7eoJWiDw70r/CYp8CYzFJsWfucJRyh0N8UIgCwCVe0h55+bM9c1D76U4rSkdUpu9ArAdJ3QOIEPBomdIBuhCj9LywtLGHArxo8QZqY5XLoZsmzwBp5LVKza97EacROoSOkwlaVuC3DLwho4dQKcpb3lmtCC1AYLT5xhyD1rqLXkcl4rvCCCrRsokZ78BFSPROudH7BFH3cDqFF5bS0dDmMfSJP7pXToQDrG4wnUzjvvO+Ax+OSpc2b7PSqntX4sXD+ico00g0m/7nwS/REmcS4C885Ji9RN6YoCW4ZnXlz4M=}
provider:
  win: azure
